version: '3'

services:
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=curt
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
  db-test:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=curt
    ports:
      - 27018:27017
    volumes:
      - ./db-test:/data/db
    restart: always
